version: "2"
services:
  d4a_app:
    image: univpm/d4apilot
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - d4a_mongodb
  d4a_mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"